// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

Future<void> main() async {}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7bQf1-pDT5Wsc5FPPoT4usYDWtjLF_QI',
    appId: '1:1073091193746:web:8bfcc937d13a847b742f4b',
    messagingSenderId: '1073091193746',
    projectId: 'fir-pokemon-app-flutter',
    authDomain: 'fir-pokemon-app-flutter.firebaseapp.com',
    storageBucket: 'fir-pokemon-app-flutter.appspot.com',
    measurementId: 'G-71F6V7MXN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJHCwymW78OFytiTxGldQ_DWTmVwQl8TM',
    appId: '1:1073091193746:android:d15500eb40164abf742f4b',
    messagingSenderId: '1073091193746',
    projectId: 'fir-pokemon-app-flutter',
    storageBucket: 'fir-pokemon-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJsJEVXkUnxB8wl--70UtLd2dvdsFaWw',
    appId: '1:1073091193746:ios:1c659084089a1346742f4b',
    messagingSenderId: '1073091193746',
    projectId: 'fir-pokemon-app-flutter',
    storageBucket: 'fir-pokemon-app-flutter.appspot.com',
    iosClientId:
        '1073091193746-p7tva8ccssngknttg4taojerohgg3plf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJsJEVXkUnxB8wl--70UtLd2dvdsFaWw',
    appId: '1:1073091193746:ios:b56777a0123ec52c742f4b',
    messagingSenderId: '1073091193746',
    projectId: 'fir-pokemon-app-flutter',
    storageBucket: 'fir-pokemon-app-flutter.appspot.com',
    iosClientId:
        '1073091193746-sjt19vf5rfabva062gceckof6cpnq07j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
